import pygame as pg
from time import sleep

pg.init()


def fadeout(screen):
    BlackboxPath = "./assets/art/blackscreen-320x320.png"
    Blackbox = pg.image.load(BlackboxPath).convert_alpha()

    transitionSpeed = 0.15

    screen.blit(Blackbox, (0,0))
    pg.display.flip()
    sleep(transitionSpeed)
    screen.blit(Blackbox, (0,320))
    pg.display.flip()
    sleep(transitionSpeed)
    screen.blit(Blackbox, (0,640))
    pg.display.flip()
    sleep(transitionSpeed)
    screen.blit(Blackbox, (320,0))
    pg.display.flip()
    sleep(transitionSpeed)
    screen.blit(Blackbox, (320,320))
    pg.display.flip()
    sleep(transitionSpeed)
    screen.blit(Blackbox, (320,640))
    pg.display.flip()
    sleep(transitionSpeed)
    screen.blit(Blackbox, (640,0))
    pg.display.flip()
    sleep(transitionSpeed)
    screen.blit(Blackbox, (640,320))
    pg.display.flip()
    sleep(transitionSpeed)
    screen.blit(Blackbox, (640,640))
    pg.display.flip()
    sleep(transitionSpeed)
    screen.blit(Blackbox, (960,0))
    pg.display.flip()
    sleep(transitionSpeed)
    screen.blit(Blackbox, (960,320))
    pg.display.flip()
    sleep(transitionSpeed)
    screen.blit(Blackbox, (960,640))
    pg.display.flip()
    sleep(transitionSpeed)

def fadein(screen, background):
    transitionSpeed = 0.15
    BlackboxPath = "./assets/art/blackscreen-320x320.png"
    Blackbox = pg.image.load(BlackboxPath).convert_alpha()

    screen.blit(background, (0,0))
    screen.blit(Blackbox, (0,0))
    screen.blit(Blackbox, (0,320))
    screen.blit(Blackbox, (0,640))
    screen.blit(Blackbox, (320,0))
    screen.blit(Blackbox, (320,320))
    screen.blit(Blackbox, (320,640))
    screen.blit(Blackbox, (640,0))
    screen.blit(Blackbox, (640,320))
    screen.blit(Blackbox, (640,640))
    screen.blit(Blackbox, (960,0))
    screen.blit(Blackbox, (960,320))
    screen.blit(Blackbox, (960,640))
    pg.display.flip()
    sleep(transitionSpeed)

    screen.blit(background, (0,0))
    screen.blit(Blackbox, (0,0))
    screen.blit(Blackbox, (0,320))
    screen.blit(Blackbox, (0,640))
    screen.blit(Blackbox, (320,0))
    screen.blit(Blackbox, (320,320))
    screen.blit(Blackbox, (320,640))
    screen.blit(Blackbox, (640,0))
    screen.blit(Blackbox, (640,320))
    screen.blit(Blackbox, (640,640))
    screen.blit(Blackbox, (960,0))
    screen.blit(Blackbox, (960,320))
    pg.display.flip()
    sleep(transitionSpeed)

    screen.blit(background, (0,0))
    screen.blit(Blackbox, (0,0))
    screen.blit(Blackbox, (0,320))
    screen.blit(Blackbox, (0,640))
    screen.blit(Blackbox, (320,0))
    screen.blit(Blackbox, (320,320))
    screen.blit(Blackbox, (320,640))
    screen.blit(Blackbox, (640,0))
    screen.blit(Blackbox, (640,320))
    screen.blit(Blackbox, (640,640))
    screen.blit(Blackbox, (960,0))
    pg.display.flip()
    sleep(transitionSpeed)

    screen.blit(background, (0,0))
    screen.blit(Blackbox, (0,0))
    screen.blit(Blackbox, (0,320))
    screen.blit(Blackbox, (0,640))
    screen.blit(Blackbox, (320,0))
    screen.blit(Blackbox, (320,320))
    screen.blit(Blackbox, (320,640))
    screen.blit(Blackbox, (640,0))
    screen.blit(Blackbox, (640,320))
    screen.blit(Blackbox, (640,640))
    pg.display.flip()
    sleep(transitionSpeed)

    screen.blit(background, (0,0))
    screen.blit(Blackbox, (0,0))
    screen.blit(Blackbox, (0,320))
    screen.blit(Blackbox, (0,640))
    screen.blit(Blackbox, (320,0))
    screen.blit(Blackbox, (320,320))
    screen.blit(Blackbox, (320,640))
    screen.blit(Blackbox, (640,0))
    screen.blit(Blackbox, (640,320))
    pg.display.flip()
    sleep(transitionSpeed)

    screen.blit(background, (0,0))
    screen.blit(Blackbox, (0,0))
    screen.blit(Blackbox, (0,320))
    screen.blit(Blackbox, (0,640))
    screen.blit(Blackbox, (320,0))
    screen.blit(Blackbox, (320,320))
    screen.blit(Blackbox, (320,640))
    screen.blit(Blackbox, (640,0))
    pg.display.flip()
    sleep(transitionSpeed)

    screen.blit(background, (0,0))
    screen.blit(Blackbox, (0,0))
    screen.blit(Blackbox, (0,320))
    screen.blit(Blackbox, (0,640))
    screen.blit(Blackbox, (320,0))
    screen.blit(Blackbox, (320,320))
    screen.blit(Blackbox, (320,640))
    pg.display.flip()
    sleep(transitionSpeed)

    screen.blit(background, (0,0))
    screen.blit(Blackbox, (0,0))
    screen.blit(Blackbox, (0,320))
    screen.blit(Blackbox, (0,640))
    screen.blit(Blackbox, (320,0))
    screen.blit(Blackbox, (320,320))
    pg.display.flip()
    sleep(transitionSpeed)

    screen.blit(background, (0,0))
    screen.blit(Blackbox, (0,0))
    screen.blit(Blackbox, (0,320))
    screen.blit(Blackbox, (0,640))
    screen.blit(Blackbox, (320,0))
    pg.display.flip()
    sleep(transitionSpeed)

    screen.blit(background, (0,0))
    screen.blit(Blackbox, (0,0))
    screen.blit(Blackbox, (0,320))
    screen.blit(Blackbox, (0,640))
    pg.display.flip()
    sleep(transitionSpeed)

    screen.blit(background, (0,0))
    screen.blit(Blackbox, (0,0))
    screen.blit(Blackbox, (0,320))
    pg.display.flip()
    sleep(transitionSpeed)

    screen.blit(background, (0,0))
    screen.blit(Blackbox, (0,0))
    pg.display.flip()
    sleep(transitionSpeed)

    screen.blit(background, (0,0))
    pg.display.flip()
    sleep(0.1)